---
# This playbook provisions a set of Jepsen nodes, and invokes Jepsen on the control node

- hosts: jepsen_nodes
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: id_rsa
    flink_url: http://apache.mirror.iphh.net/flink/flink-1.5.0/flink-1.5.0-bin-hadoop28-scala_2.11.tgz
    run_count: 3
    jepsen_root: "{{ playbook_dir }}/flink/flink-jepsen/"
    test_suite: yarn-session

  tasks:
  - name: "Install rsync"
    apt:
      name:
        - rsync
      update_cache: yes
    become: yes
    tags:
      - packages
      - rsync

  - name: "Copy ssh private key"
    copy:
      src: ./id_rsa
      dest: ~/.ssh/id_rsa
      mode: 0400
    tags:
      - ssh-key

  - name: "Copy Jepsen files to controller"
    synchronize:
      src: "{{ jepsen_root }}"
      dest: ~/
      rsync_opts: [
        "--no-motd",
        "--include=bin",
        "--include=bin/**",
        "--include=project.clj",
        "--include=scripts",
        "--include=scripts/**",
        "--include=src",
        "--include=src/**",
        "--include=test",
        "--include=test/**",
        "--exclude=*"
      ]
    when: inventory_hostname in groups['jepsen_controller']
    tags:
      - copy

  - name: "Copy run-tests.sh to controller"
    synchronize:
      src: "{{ playbook_dir }}/"
      dest: ~/
      rsync_opts: [
        "--no-motd",
        "--include=run-tests.sh",
        "--exclude=*"
      ]
    when: inventory_hostname in groups['jepsen_controller']
    tags:
      - copy

  - name: "Install extra dependencies"
    apt:
      name:
        - awscli
        - ca-certificates-java
        - curl
        - git
        - gnuplot
        - libjna-java
        - software-properties-common
        - tmux
        - vim
        - wget
      update_cache: yes
    become: yes
    tags:
      - packages

  - name: "Install extra dependencies from backports"
    apt:
      name:
        - openjdk-8-jdk
        - openjdk-8-jre-headless
      default_release: jessie-backports
      update_cache: yes
    become: yes
    tags:
      - java
      - packages

  - name: "Remove java 7"
    apt:
      name:
        - openjdk-7-jre-headless
      state: absent
      purge: yes
    become: yes
    tags:
      - java
      - packages

  - name: "Download and install leiningen"
    get_url:
      url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
      dest: /usr/bin/lein
      mode: 0555
    become: yes
    tags:
      - lein

  - name: "Run the tests"
    shell: "~/run-tests.sh {{ run_count }} {{ flink_url }} {{ test_suite }}"
    when: inventory_hostname in groups['jepsen_controller']
    register: run_tests
    ignore_errors: yes
    tags:
      - tests

  - name: "Fetch the results"
    synchronize:
      mode: pull
      src: /home/admin/
      dest: ./
      rsync_opts: [
        "--no-motd",
        "--include=store",
        "--include=store/**",
        "--exclude=*",
      ]
    when: inventory_hostname in groups['jepsen_controller']
    tags:
      - fetch

  - name: "Write out tests status"
    copy:
      content: "{{ run_tests.rc }}"
      dest: ./FAILED
    delegate_to: localhost
    when: inventory_hostname in groups['jepsen_controller'] and run_tests.rc != 0
    tags:
      - failed
